spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.8/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    path: /sell
  port: 80

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: sell.log
#  level:
#    root: warn
#    com.yx.sell: debug